/*
 * RoadPassion CONFIDENTIAL
 *
 * Copyright 2013 RoadPassion Electronics Co., Ltd.
 *
 * DO NOT COPY AND/OR REDISTRIBUTE WITHOUT PERMISSION.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */
#include "C02_PV.h"
//#include "C02_TESTER_PV/C02_TESTER_PV.h"
//#include "C06_PV/C06_PV.h"
//#include "C06TX_PV/C06TX_PV.h"
//#include "C06_AUTO_PV/C06AUTO_PV.h"



PV::PV() {
	// TODO Auto-generated constructor stub
}

PV::~PV() {
	// TODO Auto-generated destructor stub
}

PV *PV::getPV(void)
{
	printf("PV\n");
	PV *p;
	p = new C02_PV;
//#if defined(PRODUCT_VARIANT_C02)
//    p = new C02_PV;
//#elif defined(PRODUCT_VARIANT_C02_TESTER)
//    p = new C02_TESTER_PV;
//#elif defined(PRODUCT_VARIANT_C06)
//    p = new C06_PV;
//#elif defined(PRODUCT_VARIANT_C06TX)
//    p = new C06TX_PV;
//#elif defined(PRODUCT_VARIANT_C06AUTO)
    //p = new C06AUTO_PV;

//#else
//#error Please choose a proper product variant.
//#endif

	return p;
}

void getPV_run(void)
{
	PV::getPV()->run();
}

